### ISSUE TITLE
Failure to display user-friendly names in generated spreadsheet.

### ISSUE THREAD

**Issue by malloryfreeberg** [HumanCellAtlas/ingest-client#15]
Using the build_spreadsheet_with_links.py in @hewgreen 's branch (mg-links_builderv2), the following fields failed to display the user-friendly names in the column header (row 1):

```
donor_organism.organism_age_unit.text
donor_organism.development_stage.text
donor_organism.gestational_age_unit.text
donor_organism.height_unit.text
donor_organism.weight_unit.text
donor_organism.timecourse.unit.text
specimen_from_organism.organ.text
specimen_from_organism.organ_part.text
specimen_from_organism.preservation_storage.storage_time_unit.text
cell_suspension.cell_morphology.cell_size_unit.text
cell_suspension.timecourse.unit.text
collection_protocol.method.text
dissociation_protocol.method.text
enrichment_protocol.enrichment_method.text
library_preparation_protocol.input_nucleic_acid_molecule.text
library_preparation_protocol.library_construction_method.text
library_preparation_protocol.library_preamplification_method.text
library_preparation_protocol.cdna_library_amplification_method.text
sequencing_protocol.instrument_manufacturer_model.text
sequencing_protocol.method.text
```

It looks like all of these fields reference ontologies, but not all ontologized fields have this failure. For example, the fields `donor_organism.human_specific.ethnicity.text` and `donor_organism.genus_species.text` generate the correct user-friendly names.

Excel file attached.

[generic_with_links.xlsx](https://github.com/HumanCellAtlas/ingest-client/files/2875419/generic_with_links.xlsx)

**Comment by daniwelter** [comment]
Could you please confirm that this is still an issue with the latest version of the spreadsheet builder? I just did a test run and all user friendly names are correct and as expected.

**Comment by malloryfreeberg** [comment]
Just checked. LGTM! Closing the issue.
