### ISSUE TITLE
UUID fields aren't recognised as external reference field in the Schema Template lib

### ISSUE THREAD

**Issue by aaclan-ebi** [HumanCellAtlas/ingest-client#61]
Steps To Repro:
schema_template.lookup_property_attributes_in_metadata('project.uuid')

Actual Behavior:
{UnknownKeySchemaException}ERROR: Cannot find key uuid in any schema!

Expected Behavior
should return the same as the old behavior
{
    'external_reference' : True,
    'identifiable': True
}

It looks like that uuid fields is being explicitly added before as part of the schema template output

https://github.com/HumanCellAtlas/ingest-client/blob/b769486414c3d9608d05a284ff61dea0f57026b7/ingest/template/schema_parser.py#L74

Since the uuid field isn't really part of the metadata schema, the logic to handle it in the current code is not going to be applied.

https://github.com/HumanCellAtlas/ingest-client/blob/2183830cd5eab5ffec73b62a90d37fe68f69ff7e/ingest/template/descriptor.py#L128

**Comment by justincc** [comment]
This is a regression?

**Comment by aaclan-ebi** [comment]
> This is a regression?

Yes. It was a special logic in the schema template lib. I considered moving that logic in the importer since that logic is only used there but decided to keep it in the schema template as custom properties added on top of metadata schema. (See PR ^ for the changes)
