### ISSUE TITLE
project_shortname -> project_short_name

### ISSUE THREAD

**Issue by simonjupp** [HumanCellAtlas/ingest-client#7]
There's been a change in the schema that is causing and error when you run the exporter in dry run mode as we use `shortname` to create the filename. We probably want to avoid using the short name for filename and simply use what we would call the file when we export for real e.g. project_0.json

https://github.com/HumanCellAtlas/ingest-client/blob/fa441a58e2ebacc8f7a16f6c40790ad473fd92df/ingest/exporter/ingestexportservice.py#L581

**Comment by aaclan-ebi** [comment]
@simonjupp which branch are you using? I think you may be using an outdated version of the script. The latest of master is no longer using the project short name when dumping files.

**Comment by simonjupp** [comment]
I’m using the released version from pypi. I found that reference to it in the dev branch (see link above)

**Comment by aaclan-ebi** [comment]
I see, okies, the latest version isn't released yet to PyPi. We can release it once we deploy its clients to staging after being tested & monitored in integration. This would ensure that the released version is stable. Workaround for now is to clone the ingest-client repo and use editable mode of pip install. There's also an export cli script inside ingest-client that can be used. 

`$ python cli.py --submissionEnvelopeUuid=21ec3581-abc2-4e1c-9fd4-abce09aa5c19 --processUuid=b3f91034-f0de-4fb0-a038-b011b9f231b6 --ingest=http://api.ingest.dev.data.humancellatlas.org --dry
`
